---
- name: "ARO Upgrade - Fase 1: Pré-Checagem e Preparação"
  hosts: localhost
  gather_facts: false

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  environment:
    http_proxy: ""
    https_proxy: ""
    no_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
    NO_PROXY: ""
   
  roles:
    - role: pre_check_aro