---
- name: Create empty file
  ansible.builtin.file:
    path: /tmp/vars.txt
    state: touch

- name: Append dynamic tags to file
  ansible.builtin.lineinfile:
    path: /tmp/vars.txt
    line: "{{ redhat_image }}: {{ redhat_image_tags }}"
    insertafter: EOF
  vars:
        - redhat_image: 'test123'
        - redhat_image_tags: '1.21, 1.22, 1.23'     
---
- name: Include appended tags for later use
  ansible.builtin.include_vars:
    file: /tmp/vars.txt

- name: Display appended tags
  debug:
    var: test123

- name: Remove file
  ansible.builtin.file:
    path: /tmp/vars.txt
    state: absent

---
- name: Copy a file on the remote machine for editing
  ansible.builtin.copy:
    src: /tmp/vars.txt
    dest: /tmp/vars.txt
    remote_src: yes
