# ansible_aro_upgrade_project/playbooks/fase_1_preparation.yml
---
- name: Fase 1 - Preparação, Análise de Caminho e Pré-Checks para Cluster ARO
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    # Variável OBRIGATÓRIA a ser passada pelo AAP (via Survey ou variáveis do Job Template)
    aro_cluster_identifier: "{{ aro_cluster_identifier_from_survey | default('unset_cluster_identifier') }}"

  pre_tasks:
    - name: Validar se aro_cluster_identifier foi fornecido
      ansible.builtin.fail:
        msg: "A variável 'aro_cluster_identifier' é obrigatória e não foi definida. Por favor, forneça via Survey do AAP."
      when: aro_cluster_identifier == 'unset_cluster_identifier'

    - name: Exibir informações da execução
      ansible.builtin.debug:
        msg:
          - "Iniciando Fase 1 para o Cluster: {{ aro_cluster_identifier }}"
          - "Diretório base para artefatos: {{ local_artifact_base_path }}"
          - "Versão EUS Alvo Final: {{ target_final_eus_major_minor }}"

  roles:
    - role: aro_f1_checks
      vars:
        current_cluster_identifier: "{{ aro_cluster_identifier }}"