USE [master]
GO

/****** Object:  Database [DBDINDIN]    Script Date: 18/05/2022 12:45:35 ******/
CREATE DATABASE [DBDINDIN]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBDINDIN', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\DBDINDIN.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBDINDIN_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\DBDINDIN_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBDINDIN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBDINDIN] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBDINDIN] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBDINDIN] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBDINDIN] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBDINDIN] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBDINDIN] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBDINDIN] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBDINDIN] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBDINDIN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBDINDIN] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBDINDIN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBDINDIN] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBDINDIN] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBDINDIN] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBDINDIN] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBDINDIN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBDINDIN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBDINDIN] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBDINDIN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBDINDIN] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBDINDIN] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBDINDIN] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBDINDIN] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBDINDIN] SET  MULTI_USER 
GO

ALTER DATABASE [DBDINDIN] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBDINDIN] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBDINDIN] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBDINDIN] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBDINDIN] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBDINDIN] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DBDINDIN] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DBDINDIN] SET  READ_WRITE 
GO


