---
- name: ARO Upgrade - Fase 3: Pós-Checagem e Finalização
  hosts: localhost
  gather_facts: false
  # As vars como final_achieved_version_stat, etc.,
  # são injetadas pelo AAP a partir do output do job anterior (set_stats).
  vars:
    # Defaults para teste local, se necessário
    cluster_name_stat: "aro_cluster_default_postcheck"
    azure_resource_group_stat: "aro_rg_default_postcheck" # Adicionado para consistência
  roles:
    - role: post_check_aro