---
- name: ARO Upgrade - Fase 1: Pré-Checagem e Preparação
  hosts: localhost
  gather_facts: false
  vars:
    # Estas variáveis devem ser passadas como extra_vars no AAP Job Template
    # Exemplo:
    # target_aro_version: "4.16.40"
    # target_channel_eus: "eus-4.16"
    # cluster_name: "myaro01"
    # azure_resource_group: "myResourceGroup" # Necessário para _perform_single_hop.yml se usar az aro upgrade
  roles:
    - role: pre_check_aro