---
- name: ARO Upgrade - Fase 2: Executar Saltos de Upgrade
  hosts: localhost
  gather_facts: false
  # As vars como cluster_name_stat, upgrade_hops_stat, etc.,
  # são injetadas pelo AAP a partir do output do job anterior (set_stats).
  vars:
    # Defaults para teste local, se necessário
    cluster_name_stat: "aro_cluster_default_upgrade"
    azure_resource_group_stat: "aro_rg_default_upgrade" # Adicionado para consistência
  roles:
    - role: upgrade_aro_hops