---
- name: "Health Check (Comum): {{ health_check_stage_name }} - Loop de verificação do ClusterVersion"
  block:
    - name: "Health Check (Comum): {{ health_check_stage_name }} - Coletar dados do ClusterVersion"
      kubernetes.core.k8s_info:
        kind: ClusterVersion
        api_version: config.openshift.io/v1
        name: version
      register: r_cv_health_common

    - name: "Health Check (Comum): {{ health_check_stage_name }} - Avaliar condição 'Available'"
      ansible.builtin.set_fact:
        _cv_available_check_common: >-
          {% set _list = r_cv_health_common.resources[0].status.conditions | selectattr('type', 'equalto', 'Available') | list %}
          {% if _list | length > 0 %}{{ _list[0].status == 'True' }}{% else %}{{ False }}{% endif %}
      when: >
        r_cv_health_common.resources is defined and
        r_cv_health_common.resources | length > 0 and
        r_cv_health_common.resources[0].status is defined and
        r_cv_health_common.resources[0].status.conditions is defined

    - name: "Health Check (Comum): {{ health_check_stage_name }} - Avaliar condição 'Progressing'"
      ansible.builtin.set_fact:
        _cv_progressing_check_common: >-
          {% set _list = r_cv_health_common.resources[0].status.conditions | selectattr('type', 'equalto', 'Progressing') | list %}
          {% if _list | length > 0 %}{{ _list[0].status == 'False' }}{% else %}{{ False }}{% endif %}
      when: >
        r_cv_health_common.resources is defined and
        r_cv_health_common.resources | length > 0 and
        r_cv_health_common.resources[0].status is defined and
        r_cv_health_common.resources[0].status.conditions is defined

    - name: "Health Check (Comum): {{ health_check_stage_name }} - Avaliar condição 'Degraded'"
      ansible.builtin.set_fact:
        _cv_degraded_check_common: >-
          {% set _list = r_cv_health_common.resources[0].status.conditions | selectattr('type', 'equalto', 'Degraded') | list %}
          {% if _list | length > 0 %}{{ _list[0].status == 'False' }}{% else %}{{ True }}{% endif %}
      when: >
        r_cv_health_common.resources is defined and
        r_cv_health_common.resources | length > 0 and
        r_cv_health_common.resources[0].status is defined and
        r_cv_health_common.resources[0].status.conditions is defined

    - name: "Health Check (Comum): {{ health_check_stage_name }} - Definir status final da checagem do ClusterVersion"
      ansible.builtin.set_fact:
        _cv_health_passed_common: >-
          {{ (r_cv_health_common.resources is defined and
              r_cv_health_common.resources | length > 0 and
              r_cv_health_common.resources[0].status is defined and
              r_cv_health_common.resources[0].status.conditions is defined and
              (_cv_available_check_common | default(false) | bool) and
              (_cv_progressing_check_common | default(false) | bool) and
              (_cv_degraded_check_common | default(false) | bool) )
          }}

  retries: 5
  delay: 15
  until: _cv_health_passed_common | default(false) | bool

- name: "Health Check (Comum): {{ health_check_stage_name }} - Verificar ClusterOperators"
  kubernetes.core.k8s_info:
    kind: ClusterOperator
    api_version: config.openshift.io/v1
  register: r_co_health_common
  retries: 3
  delay: 10

- name: "Health Check (Comum): {{ health_check_stage_name }} - Validar status dos ClusterOperators"
  ansible.builtin.assert:
    that:
      - not item.status.conditions | selectattr('type', 'equalto', 'Available') | selectattr('status', 'equalto', 'False') | list
      - not item.status.conditions | selectattr('type', 'equalto', 'Progressing') | selectattr('status', 'equalto', 'True') | list
      - not item.status.conditions | selectattr('type', 'equalto', 'Degraded') | selectattr('status', 'equalto', 'True') | list
    fail_msg: "ClusterOperator {{ item.metadata.name }} em {{ health_check_stage_name }} não está saudável. Condições: {{ item.status.conditions }}"
    quiet: true
  loop: "{{ r_co_health_common.resources }}"
  loop_control:
    label: "{{ item.metadata.name }}"

- name: "Health Check (Comum): {{ health_check_stage_name }} - Verificar Nós"
  kubernetes.core.k8s_info:
    kind: Node
    api_version: v1
  register: r_node_health_common

- name: "Health Check (Comum): {{ health_check_stage_name }} - Validar status dos Nós"
  ansible.builtin.assert:
    that:
      - item.status.conditions | selectattr('type', 'equalto', 'Ready') | selectattr('status', 'equalto', 'True') | list
    fail_msg: "Nó {{ item.metadata.name }} em {{ health_check_stage_name }} não está Ready. Condições: {{ item.status.conditions }}"
    quiet: true
  loop: "{{ r_node_health_common.resources }}"
  loop_control:
    label: "{{ item.metadata.name }}"

- name: "Health Check (Comum): {{ health_check_stage_name }} - Sumário"
  ansible.builtin.debug:
    msg:
      - "Saúde do Cluster ({{ health_check_stage_name }}): OK"
      - "Versão Desejada Atual: {{ r_cv_health_common.resources[0].status.desired.version }}"
      - "ClusterOperators: {{ r_co_health_common.resources | length }} operadores, todos saudáveis."
      - "Nós: {{ r_node_health_common.resources | length }} nós, todos Ready."