# roles/aro_f1_checks/tasks/check_custom_configs.yml
---
# Vars globais da role: current_cluster_identifier, check_mode, artifact_dir
# Vars opcionais para autenticação: _openshift_auth_host_role, _openshift_auth_api_key_role, _openshift_validate_certs_role

- name: "CHECK_CUSTOM_CONFIGS ({{ check_mode }}) | Listar TODOS os PodDisruptionBudgets (PDBs) do Cluster"
  kubernetes.core.k8s_info:
    api_version: policy/v1
    kind: PodDisruptionBudget
    host: "{{ _openshift_auth_host_role | default(omit) }}"
    api_key: "{{ _openshift_auth_api_key_role | default(omit) }}"
    validate_certs: "{{ _openshift_validate_certs_role | default(omit) }}"
  register: r_all_cluster_pdbs_in_phase
  ignore_errors: yes

- name: "CHECK_CUSTOM_CONFIGS ({{ check_mode }}) | Processar e Salvar PDBs (usando include)"
  ansible.builtin.include_tasks: process_pdb_listing.yml
  vars:
    pdbs_resources_to_process: "{{ r_all_cluster_pdbs_in_phase.resources | default([]) }}"
    # artifact_dir, current_cluster_identifier, check_mode são herdados
  when: r_all_cluster_pdbs_in_phase.resources is defined

- name: "CHECK_CUSTOM_CONFIGS ({{ check_mode }}) | Placeholder para outras verificações"
  ansible.builtin.debug:
    msg: "Implementar outras verificações de configurações customizadas para {{ current_cluster_identifier }} no modo {{ check_mode }}."