# ansible_aro_upgrade_project/roles/aro_f1_checks/tasks/main.yml
---
# Vars globais da role: current_cluster_identifier, check_mode, artifact_dir
# Vars opcionais para autenticação (se não usar credencial token AAP):
# _openshift_auth_host_role, _openshift_auth_api_key_role, _openshift_validate_certs_role

- name: Criar diretório de artefatos para {{ check_mode }} do cluster {{ current_cluster_identifier }}
  ansible.builtin.file:
    path: "{{ artifact_dir }}"
    state: directory
    mode: '0755'
  run_once: true # Para garantir que seja criado apenas uma vez por execução do play

- name: "COLETA | Coletar Informações Essenciais do Cluster ({{ check_mode }})"
  ansible.builtin.include_tasks: get_cluster_info.yml

# A avaliação do caminho de upgrade e APIs depreciadas só faz sentido no pré-check
- name: "AVALIAÇÃO | Avaliar Caminho de Upgrade Inicial e Próximos Saltos Lógicos"
  ansible.builtin.include_tasks: assess_initial_path.yml
  when:
    - aro_cluster_info.cluster_version_obj is defined # Garante que a coleta base funcionou
    - check_mode == "pre_upgrade"

- name: "INFORMATIVO | Verificar APIs Depreciadas ({{ check_mode }})"
  ansible.builtin.include_tasks: check_deprecated_apis_info_only.yml
  when:
    - check_mode == "pre_upgrade" # Apenas no pré-check informativo
    - aro_cluster_info.cluster_version_obj is defined

- name: "VERIFICAÇÃO | Verificar Recursos do Cluster ({{ check_mode }})"
  ansible.builtin.include_tasks: check_resources.yml
  when: aro_cluster_info.cluster_version_obj is defined

- name: "VERIFICAÇÃO | Listar Configurações de PDBs ({{ check_mode }})"
  ansible.builtin.include_tasks: check_custom_configs.yml # Inclui process_pdb_listing.yml
  when: aro_cluster_info.cluster_version_obj is defined

- name: "INFORMATIVO | Verificar Pods Problemáticos ({{ check_mode }})"
  ansible.builtin.include_tasks: check_problematic_pods_info_only.yml
  when: aro_cluster_info.cluster_version_obj is defined