---
- name: Validar se todas as variáveis obrigatórias foram fornecidas e formato do canal
  ansible.builtin.assert:
    that:
      - target_aro_version is defined and target_aro_version | length > 0
      - target_channel_eus is defined and target_channel_eus is match("^eus-\\d+\\.\\d+$")
      - cluster_name is defined and cluster_name | length > 0
      - azure_resource_group is defined and azure_resource_group | length > 0
    fail_msg: "As variáveis 'target_aro_version', 'target_channel_eus' (formato eus-X.Y), 'cluster_name', e 'azure_resource_group' são obrigatórias."
    quiet: true

- name: Validar correspondência entre target_aro_version e target_channel_eus
  vars:
    target_version_minor_part: "{{ target_aro_version.split('.')[0] }}.{{ target_aro_version.split('.')[1] }}"
    channel_minor_part: "{{ target_channel_eus.split('-')[1] }}"
  ansible.builtin.assert:
    that:
      - target_version_minor_part == channel_minor_part
    fail_msg: >
      A parte major.minor da 'target_aro_version' ({{ target_version_minor_part }})
      não corresponde à parte major.minor do 'target_channel_eus' ({{ channel_minor_part }}).
    quiet: true

- name: "Debug: Variáveis de entrada para Cluster {{ cluster_name }}"
  ansible.builtin.debug:
    msg:
      - "Cluster para Upgrade: {{ cluster_name }}"
      - "Resource Group: {{ azure_resource_group }}"
      - "Versão Alvo do Upgrade: {{ target_aro_version }}"
      - "Canal EUS Alvo: {{ target_channel_eus }}"