---
- name: "Health Check: {{ health_check_stage_name }} - Loop de verificação do ClusterVersion"
  block:
    - name: "Health Check: {{ health_check_stage_name }} - Coletar dados do ClusterVersion"
      kubernetes.core.k8s_info:
        kind: ClusterVersion
        api_version: config.openshift.io/v1
        name: version
      register: r_cv_health

    - name: "Health Check: {{ health_check_stage_name }} - Avaliar condição 'Available'"
      ansible.builtin.set_fact:
        _cv_available_check: >-
          {% set _list = r_cv_health.resources[0].status.conditions | selectattr('type', 'equalto', 'Available') | list %}
          {% if _list | length > 0 %}{{ _list[0].status == 'True' }}{% else %}{{ False }}{% endif %}
      when: >
        r_cv_health.resources is defined and
        r_cv_health.resources | length > 0 and
        r_cv_health.resources[0].status is defined and
        r_cv_health.resources[0].status.conditions is defined

    - name: "Health Check: {{ health_check_stage_name }} - Avaliar condição 'Progressing'"
      ansible.builtin.set_fact:
        _cv_progressing_check: >-
          {% set _list = r_cv_health.resources[0].status.conditions | selectattr('type', 'equalto', 'Progressing') | list %}
          {% if _list | length > 0 %}{{ _list[0].status == 'False' }}{% else %}{{ False }}{% endif %}
      when: >
        r_cv_health.resources is defined and
        r_cv_health.resources | length > 0 and
        r_cv_health.resources[0].status is defined and
        r_cv_health.resources[0].status.conditions is defined

    - name: "Health Check: {{ health_check_stage_name }} - Avaliar condição 'Degraded'"
      ansible.builtin.set_fact:
        _cv_degraded_check: >-
          {% set _list = r_cv_health.resources[0].status.conditions | selectattr('type', 'equalto', 'Degraded') | list %}
          {% if _list | length > 0 %}{{ _list[0].status == 'False' }}{% else %}{{ True }}{% endif %}
      when: >
        r_cv_health.resources is defined and
        r_cv_health.resources | length > 0 and
        r_cv_health.resources[0].status is defined and
        r_cv_health.resources[0].status.conditions is defined

    - name: "Health Check: {{ health_check_stage_name }} - Definir status final da checagem do ClusterVersion"
      ansible.builtin.set_fact:
        _cv_health_passed: >-
          {{ (r_cv_health.resources is defined and
              r_cv_health.resources | length > 0 and
              r_cv_health.resources[0].status is defined and
              r_cv_health.resources[0].status.conditions is defined and
              (_cv_available_check | default(false) | bool) and
              (_cv_progressing_check | default(false) | bool) and
              (_cv_degraded_check | default(false) | bool) )
          }}
      # Garante que _cv_health_passed só seja true se todas as checagens anteriores definiram suas vars e elas são true
      # Os defaults para as vars _cv_..._check são false para garantir que se a condição when anterior não rodou, a checagem falha.

  # O loop until agora opera no bloco e verifica a variável _cv_health_passed
  retries: 5
  delay: 15
  until: _cv_health_passed | default(false) | bool

- name: "Health Check: {{ health_check_stage_name }} - Verificar ClusterOperators"
  kubernetes.core.k8s_info:
    kind: ClusterOperator
    api_version: config.openshift.io/v1
  register: r_co_health
  retries: 3
  delay: 10

- name: "Health Check: {{ health_check_stage_name }} - Validar status dos ClusterOperators"
  ansible.builtin.assert:
    that:
      - not item.status.conditions | selectattr('type', 'equalto', 'Available') | selectattr('status', 'equalto', 'False') | list
      - not item.status.conditions | selectattr('type', 'equalto', 'Progressing') | selectattr('status', 'equalto', 'True') | list
      - not item.status.conditions | selectattr('type', 'equalto', 'Degraded') | selectattr('status', 'equalto', 'True') | list
    fail_msg: "ClusterOperator {{ item.metadata.name }} em {{ health_check_stage_name }} não está saudável. Condições: {{ item.status.conditions }}"
    quiet: true
  loop: "{{ r_co_health.resources }}"
  loop_control:
    label: "{{ item.metadata.name }}"

- name: "Health Check: {{ health_check_stage_name }} - Verificar Nós"
  kubernetes.core.k8s_info:
    kind: Node
    api_version: v1
  register: r_node_health

- name: "Health Check: {{ health_check_stage_name }} - Validar status dos Nós"
  ansible.builtin.assert:
    that:
      - item.status.conditions | selectattr('type', 'equalto', 'Ready') | selectattr('status', 'equalto', 'True') | list
    fail_msg: "Nó {{ item.metadata.name }} em {{ health_check_stage_name }} não está Ready. Condições: {{ item.status.conditions }}"
    quiet: true
  loop: "{{ r_node_health.resources }}"
  loop_control:
    label: "{{ item.metadata.name }}"

- name: "Health Check: {{ health_check_stage_name }} - Sumário"
  ansible.builtin.debug:
    msg:
      - "Saúde do Cluster ({{ health_check_stage_name }}): OK"
      - "Versão Desejada Atual: {{ r_cv_health.resources[0].status.desired.version }}"
      - "ClusterOperators: {{ r_co_health.resources | length }} operadores, todos saudáveis."
      - "Nós: {{ r_node_health.resources | length }} nós, todos Ready."