# tasks/process_report_data.yml
- name: Initialize enriched results and executive summary structure
  ansible.builtin.set_fact:
    enriched_comparison_results: []
    executive_summary_data:
      cluster_operators: { antes: [], depois: [] }
      deployments: { antes_total: 0, antes_problematic: 0, depois_total: 0, depois_problematic: 0 }
      pods: { antes_problematic_count: 0, depois_problematic_count: 0 }

# ADICIONE ESTA TASK DE DEBUG AQUI:
- name: "DEBUG: Conteúdo de comparison_results ANTES do loop"
  ansible.builtin.debug:
    var: comparison_results
    verbosity: 2 # Tenta mostrar a estrutura completa, mesmo que profunda

- name: "Process and Enrich Data for Report (STATIC NAME FOR DEBUG)" # NOME SIMPLIFICADO
  ansible.builtin.include_tasks: process_report_data_item.yml
  loop: "{{ comparison_results | default([]) }}" # Expressão suspeita
  loop_control:
    loop_var: comp_item
    label: "Processing Kind: {{ comp_item.kind | default('DESCONHECIDO') }}" # Label simplificado
  # Condição 'when' mais segura para evitar erro se comparison_results for undefined antes do default
  when: (comparison_results | default([]) | length > 0)
  vars:
    noop: ""