---
# Analisa as atualizações disponíveis e sugere próximos passos lógicos.

- name: ASSESS_PATH | Extrair EUS major.minor atual da versão do cluster
  ansible.builtin.set_fact:
    current_eus_major_minor: "{{ aro_cluster_info.current_version.split('.')[0] }}.{{ aro_cluster_info.current_version.split('.')[1] }}"

- name: ASSESS_PATH | Calcular índice EUS atual
  ansible.builtin.set_fact:
    # Calcula o índice do EUS atual ou -1 se não encontrado. Garante que é um inteiro.
    current_eus_index_fact: >-
      {{ (eus_known_progression.index(current_eus_major_minor)
         if current_eus_major_minor in eus_known_progression else -1) | int }}

- name: ASSESS_PATH | Calcular próximo índice EUS
  ansible.builtin.set_fact:
    # Adiciona 1 ao índice atual. O resultado será um inteiro.
    next_eus_index_fact: "{{ current_eus_index_fact + 1 }}"

- name: ASSESS_PATH | Determinar condição para calcular próximo EUS lógico
  ansible.builtin.set_fact:
    # Define uma flag booleana para a condição. Ambas as comparações são entre inteiros.
    _can_determine_next_logical_eus: >-
      {{ (current_eus_index_fact != -1) and
         (next_eus_index_fact < (eus_known_progression | length)) }}

- name: ASSESS_PATH | Definir próximo EUS major.minor lógico
  ansible.builtin.set_fact:
    # Usa a flag e o índice para acessar a lista. O índice é forçado para int por segurança.
    next_logical_eus_major_minor: >-
      {{ eus_known_progression[(next_eus_index_fact | int)]
         if _can_determine_next_logical_eus
         else 'N/A' }}

- name: ASSESS_PATH | Verificar se já estamos no EUS minor alvo ou além
  ansible.builtin.set_fact:
    assessment_already_at_or_beyond_target_eus: "{{ (current_eus_major_minor >= target_final_eus_major_minor) }}"

- name: ASSESS_PATH | Procurar por atualização Z-stream recomendada DENTRO do canal EUS ATUAL
  vars:
    # Esta expressão complexa permanece, mas é para um propósito diferente (filtragem de dados)
    zstream_update_candidates_in_current_eus: >-
      {{ aro_cluster_info.available_updates |
         selectattr('channel', 'defined') |
         selectattr('version', 'match', '^' + current_eus_major_minor + '\\..*') |
         selectattr('channel', 'equalto', 'eus-' + current_eus_major_minor) |
         selectattr('version', '>', aro_cluster_info.current_version) |
         sort(attribute='version', reverse=true) }}
  ansible.builtin.set_fact:
    assessment_recommended_zstream_update: "{{ zstream_update_candidates_in_current_eus | first | default({}) }}"

- name: ASSESS_PATH | Procurar por atualização para o PRÓXIMO canal EUS lógico
  vars:
    next_eus_update_candidates: >-
      {{ aro_cluster_info.available_updates |
         selectattr('channel', 'defined') |
         selectattr('version', 'match', '^' + next_logical_eus_major_minor + '\\..*') |
         selectattr('channel', 'equalto', 'eus-' + next_logical_eus_major_minor) |
         sort(attribute='version') }}
  ansible.builtin.set_fact:
    assessment_recommended_next_eus_update: "{{ next_eus_update_candidates | first | default({}) }}"
  when: next_logical_eus_major_minor != 'N/A' and next_logical_eus_major_minor is defined

- name: ASSESS_PATH | Armazenar resultado da avaliação do caminho inicial para fácil acesso
  ansible.builtin.set_fact:
    aro_initial_path_assessment:
      current_eus_is_target_or_beyond: "{{ assessment_already_at_or_beyond_target_eus }}"
      current_eus_on_cluster: "{{ current_eus_major_minor }}"
      next_logical_eus_channel: "{{ 'eus-' + next_logical_eus_major_minor if next_logical_eus_major_minor != 'N/A' and next_logical_eus_major_minor is defined else 'N/A' }}"
      recommended_zstream_update: "{{ assessment_recommended_zstream_update }}"
      recommended_next_eus_update: "{{ assessment_recommended_next_eus_update | default({}) }}"

- name: ASSESS_PATH | Debug da avaliação do caminho inicial
  ansible.builtin.debug:
    var: aro_initial_path_assessment
    verbosity: 1