# ansible_aro_upgrade_project/roles/aro_f1_checks/tasks/check_resources.yml
---
- name: CHECK_RESOURCES | Verificar Métricas de Recursos (Exemplo com NodeMetrics)
  kubernetes.core.k8s_info:
    kind: NodeMetrics
    api_version: metrics.k8s.io/v1beta1
  register: r_node_metrics
  ignore_errors: yes

- name: CHECK_RESOURCES | Exibir informações básicas de NodeMetrics se disponíveis
  ansible.builtin.debug:
    msg: "NodeMetrics coletadas para {{ current_cluster_identifier }}. Total de nós com métricas: {{ r_node_metrics.resources | length }}"
  when: r_node_metrics.resources is defined and r_node_metrics.resources

- name: CHECK_RESOURCES | Salvar NodeMetrics em arquivo (se coletadas)
  ansible.builtin.copy:
    content: "{{ r_node_metrics.resources | to_nice_json(indent=2) }}"
    dest: "{{ f1_artifact_dir }}/nodemetrics_pre_upgrade.json"
  when: r_node_metrics.resources is defined and r_node_metrics.resources

- name: CHECK_RESOURCES | Placeholder para verificações adicionais de recursos
  ansible.builtin.debug:
    msg: "Implementar verificações detalhadas de CPU, memória e disco para {{ current_cluster_identifier }} aqui."