# ansible_aro_upgrade_project/roles/aro_f1_checks/tasks/check_custom_configs.yml
---
- name: CHECK_CUSTOM_CONFIGS | Verificar PodDisruptionBudgets (PDBs)
  kubernetes.core.k8s_info:
    kind: PodDisruptionBudget
    api_version: policy/v1
  register: r_pdbs
  ignore_errors: yes # Continuar mesmo se não houver PDBs ou houver erro ao listar

- name: CHECK_CUSTOM_CONFIGS | Analisar PDBs e identificar configurações restritivas
  ansible.builtin.set_fact:
    problematic_pdbs_list: >-
      {{ r_pdbs.resources |
         selectattr('status.disruptionsAllowed', 'defined') |
         selectattr('status.disruptionsAllowed', '>', 0) | # Invertido: selecionar PDBs que permitem disrupções
         selectattr('status.disruptionsAllowed', '<', 1) | # Correção: selecionar PDBs que NÃO permitem disrupções (disruptionsAllowed == 0)
         map(attribute='metadata.namespace' + '/' + attribute='metadata.name') | list }}
  when: r_pdbs.resources is defined

- name: CHECK_CUSTOM_CONFIGS | Corrigir lógica para PDBs problemáticos
  ansible.builtin.set_fact:
    actually_problematic_pdbs: |
      {% set restricted_pdbs = [] %}
      {% for pdb_item in r_pdbs.resources if pdb_item.status is defined and pdb_item.status.disruptionsAllowed is defined %}
        {% if (pdb_item.status.disruptionsAllowed | int) < 1 %}
          {% set _ = restricted_pdbs.append(pdb_item.metadata.namespace ~ '/' ~ pdb_item.metadata.name) %}
        {% endif %}
      {% endfor %}
      {{ restricted_pdbs }}
  when: r_pdbs.resources is defined

- name: CHECK_CUSTOM_CONFIGS | Exibir PDBs que podem bloquear o drain de nós
  ansible.builtin.debug:
    msg: "ALERTA para {{ current_cluster_identifier }}: Os seguintes PDBs não permitem disrupções e podem bloquear o upgrade: {{ actually_problematic_pdbs }}"
  when: actually_problematic_pdbs is defined and actually_problematic_pdbs | length > 0

- name: CHECK_CUSTOM_CONFIGS | Salvar PDBs em arquivo
  ansible.builtin.copy:
    content: "{{ r_pdbs.resources | default([]) | to_nice_json(indent=2) }}"
    dest: "{{ f1_artifact_dir }}/pdbs_pre_upgrade.json"
  when: r_pdbs.resources is defined

- name: CHECK_CUSTOM_CONFIGS | Placeholder para verificações de configurações customizadas adicionais
  ansible.builtin.debug:
    msg: "Implementar verificações para webhooks, etc., para {{ current_cluster_identifier }} aqui."