---
# Coleta informações básicas do cluster, operadores, nós e MCPs.
# Módulos kubernetes.core usarão credenciais do ambiente AAP.

- name: GET_CLUSTER_INFO | Obter informações do objeto ClusterVersion 'version'
  kubernetes.core.k8s_info:
    kind: ClusterVersion
    api_version: config.openshift.io/v1
    name: version
  register: r_cv_details
  failed_when: "r_cv_details.resources | length == 0"
  retries: 3 # Adiciona resiliência para falhas transientes de rede
  delay: 10  # Espera 10s entre tentativas

- name: GET_CLUSTER_INFO | Definir fatos básicos do cluster a partir do ClusterVersion
  ansible.builtin.set_fact:
    aro_cluster_info:
      cluster_version_obj: "{{ r_cv_details.resources[0] }}"
      current_version: "{{ r_cv_details.resources[0].status.desired.version }}"
      current_channel: "{{ r_cv_details.resources[0].spec.channel | default('') }}"
      current_image: "{{ r_cv_details.resources[0].status.desired.image }}"
      available_updates: "{{ r_cv_details.resources[0].status.availableUpdates | default([]) }}"
      history: "{{ r_cv_details.resources[0].status.history | default([]) }}" # Útil para ver upgrades passados
      conditions: "{{ r_cv_details.resources[0].status.conditions | default([]) }}"
    cv_condition_available: "{{ (r_cv_details.resources[0].status.conditions | selectattr('type', 'equalto', 'Available') | map(attribute='status') | first | default('False')) == 'True' }}"
    cv_condition_progressing: "{{ (r_cv_details.resources[0].status.conditions | selectattr('type', 'equalto', 'Progressing') | map(attribute='status') | first | default('False')) == 'True' }}"
    cv_condition_degraded: "{{ (r_cv_details.resources[0].status.conditions | selectattr('type', 'equalto', 'Degraded') | map(attribute='status') | first | default('False')) == 'True' }}"

- name: GET_CLUSTER_INFO | Obter status de todos os ClusterOperators
  kubernetes.core.k8s_info:
    kind: ClusterOperator
    api_version: config.openshift.io/v1
  register: r_cluster_operators

# --- INÍCIO DA SEÇÃO CORRIGIDA PARA PROCESSAR CLUSTEROPERATORS ---
- name: GET_CLUSTER_INFO | Inicializar listas para status de ClusterOperator
  ansible.builtin.set_fact:
    _degraded_operator_names_list: []
    _not_available_operator_names_list: [] # Operadores que têm Available=False

- name: GET_CLUSTER_INFO | Iterar sobre ClusterOperators para checar condições
  ansible.builtin.set_fact:
    _degraded_operator_names_list: >-
      {{ _degraded_operator_names_list + [item.metadata.name]
         if (item.status.conditions | selectattr('type', 'equalto', 'Degraded') | selectattr('status', 'equalto', 'True') | list | length > 0)
         else _degraded_operator_names_list }}
    _not_available_operator_names_list: >-
      {{ _not_available_operator_names_list + [item.metadata.name]
         if (item.status.conditions | selectattr('type', 'equalto', 'Available') | selectattr('status', 'equalto', 'False') | list | length > 0)
         else _not_available_operator_names_list }}
  loop: "{{ r_cluster_operators.resources }}"
  when:
    - item.status is defined
    - item.status.conditions is defined

- name: GET_CLUSTER_INFO | Definir fatos finais do status dos ClusterOperators
  ansible.builtin.set_fact:
    aro_co_status:
      total: "{{ r_cluster_operators.resources | length }}"
      all_available: "{{ _not_available_operator_names_list | length == 0 }}" # True se nenhum operador estiver "Não Disponível"
      degraded_operators: "{{ _degraded_operator_names_list }}" # Lista de nomes dos operadores degradados
    aro_co_degraded_count: "{{ _degraded_operator_names_list | length }}"
# --- FIM DA SEÇÃO CORRIGIDA PARA PROCESSAR CLUSTEROPERATORS ---

- name: GET_CLUSTER_INFO | Obter status de todos os Nós (Nodes)
  kubernetes.core.k8s_info:
    kind: Node
  register: r_nodes

- name: GET_CLUSTER_INFO | Processar status dos Nós
  ansible.builtin.set_fact:
    aro_node_status:
      total: "{{ r_nodes.resources | length }}"
      ready_count: >-
        {{ r_nodes.resources |
           selectattr('status.conditions', 'selectattr', 'type', 'equalto', 'Ready') |
           selectattr('status.conditions', 'selectattr', 'status', 'equalto', 'True') | list | length }}
    aro_nodes_not_ready_list: >-
        {{ r_nodes.resources |
           # Seleciona nós onde a condição Ready não é 'True'
           selectattr('status.conditions', 'map', attribute='type', 'map', 'lower') |
           map('zip', r_nodes.resources | map(attribute='status.conditions') | map('map', attribute='status')) | # This is getting complex and likely wrong for direct 'not ready'
           # Simplificação: Lista nós que não tem a condição Ready='True'
           select('node_is_not_ready') | # Precisaria de um custom test ou refatorar
           map(attribute='metadata.name') | list }} # ESTA LINHA PRECISA DE REVISÃO PARA SIMPLICIDADE

# Simplificação para aro_nodes_not_ready_list:
- name: GET_CLUSTER_INFO | Identificar Nós Não Prontos (simplificado)
  ansible.builtin.set_fact:
    _temp_nodes_not_ready: []
- name: GET_CLUSTER_INFO | Loop para Nós Não Prontos
  ansible.builtin.set_fact:
    _temp_nodes_not_ready: "{{ _temp_nodes_not_ready + [item.metadata.name] }}"
  loop: "{{ r_nodes.resources }}"
  vars:
    node_ready_conditions: "{{ item.status.conditions | selectattr('type', 'equalto', 'Ready') | list }}"
  when:
    - item.status is defined
    - item.status.conditions is defined
    - not (node_ready_conditions | length > 0 and node_ready_conditions[0].status == 'True')

- name: GET_CLUSTER_INFO | Atualizar aro_node_status com Nós Não Prontos
  ansible.builtin.set_fact:
    aro_node_status: "{{ aro_node_status | combine({'not_ready_list': _temp_nodes_not_ready}) }}"


- name: GET_CLUSTER_INFO | Obter status dos MachineConfigPools (MCPs)
  kubernetes.core.k8s_info:
    kind: MachineConfigPool
    api_version: machineconfiguration.openshift.io/v1
  register: r_mcps

- name: GET_CLUSTER_INFO | Processar status dos MCPs
  ansible.builtin.set_fact:
    aro_mcp_status:
      all_updated: >-
        {{ not (r_mcps.resources | selectattr('status.updatedMachineCount', '!=', item.status.machineCount) | list) }} # Cuidado com 'item' aqui, deve ser dentro de um loop ou usar map/select
      degraded_mcps: >-
        {{ r_mcps.resources |
           selectattr('status.conditions', 'selectattr', 'type', 'equalto', 'Degraded') |
           selectattr('status.conditions', 'selectattr', 'status', 'equalto', 'True') |
           map(attribute='metadata.name') | list }}
      mcp_details: "{{ r_mcps.resources | items2dict(key_name='metadata.name', value_name='status') }}"

# Simplificação para aro_mcp_status:
- name: GET_CLUSTER_INFO | Inicializar status MCP (simplificado)
  ansible.builtin.set_fact:
    _temp_mcp_all_updated: true
    _temp_mcp_degraded_list: []

- name: GET_CLUSTER_INFO | Loop para status dos MCPs
  ansible.builtin.set_fact:
    _temp_mcp_all_updated: false # Se qualquer MCP não estiver atualizado, marca como false
    _temp_mcp_degraded_list: >-
      {{ _temp_mcp_degraded_list + [item.metadata.name]
         if (item.status.conditions | selectattr('type', 'equalto', 'Degraded') | selectattr('status', 'equalto', 'True') | list | length > 0)
         else _temp_mcp_degraded_list }}
  loop: "{{ r_mcps.resources }}"
  when:
    - item.status is defined
    - item.status.updatedMachineCount is defined # Garantir que os atributos existem
    - item.status.machineCount is defined
    - item.status.updatedMachineCount != item.status.machineCount or
      (item.status.conditions is defined and (item.status.conditions | selectattr('type', 'equalto', 'Degraded') | selectattr('status', 'equalto', 'True') | list | length > 0))


- name: GET_CLUSTER_INFO | Atualizar aro_mcp_status
  ansible.builtin.set_fact:
    aro_mcp_status:
      all_updated: "{{ _temp_mcp_all_updated }}"
      degraded_mcps: "{{ _temp_mcp_degraded_list }}"
      mcp_details: "{{ r_mcps.resources | items2dict(key_name='metadata.name', value_name='status') }}" # Mantém os detalhes


- name: GET_CLUSTER_INFO | Sumarizar saúde geral do cluster para display e validação rápida
  ansible.builtin.set_fact:
    aro_cluster_health_summary: >-
      CV_Available={{ cv_condition_available }},
      CV_Progressing={{ cv_condition_progressing }},
      CV_Degraded={{ cv_condition_degraded }};
      CO_All_Available={{ aro_co_status.all_available }} (Degraded_CO_Count={{ aro_co_degraded_count }});
      Nodes_Ready={{ aro_node_status.ready_count }}/{{ aro_node_status.total }} (Not_Ready_Nodes={{ aro_node_status.not_ready_list | default([]) | length }});
      MCPs_All_Updated={{ aro_mcp_status.all_updated }} (Degraded_MCP_Count={{ aro_mcp_status.degraded_mcps | length }})

- name: GET_CLUSTER_INFO | Salvar objetos coletados em um arquivo JSON para análise detalhada
  ansible.builtin.copy:
    content: |
      {
        "cluster_version": {{ aro_cluster_info | default({}) | to_nice_json }},
        "cluster_operators": {{ r_cluster_operators.resources | default([]) | to_nice_json }},
        "nodes": {{ r_nodes.resources | default([]) | to_nice_json }},
        "mcps": {{ r_mcps.resources | default([]) | to_nice_json }}
      }
    dest: "{{ f1_artifact_dir }}/cluster_objects_pre_upgrade.json" # f1_artifact_dir vem de defaults/main.yml da role
  when: aro_cluster_info is defined