# ansible_aro_upgrade_project/roles/aro_f1_checks/tasks/process_node_item.yml
---
# Este arquivo é chamado para cada 'item' (nó) do loop em get_cluster_info.yml
# A variável 'item' (representando o nó atual) está disponível aqui.
# As variáveis _temp_nodes_ready_count e _temp_nodes_not_ready_list são do escopo da role/play.

- name: "Definir 'node_is_actually_ready_now' para o Nó: {{ item.metadata.name | default('Nó sem nome') }}"
  ansible.builtin.set_fact:
    node_is_actually_ready_now: >-
      {{ (item.status.conditions | selectattr('type', 'equalto', 'Ready') | selectattr('status', 'equalto', 'True') | list | length > 0) }}

- name: "DEBUG NÓ ({{ item.metadata.name | default('Nó sem nome') }}) - ANTES da atualização de contadores"
  ansible.builtin.debug:
    msg:
      - "Processando Nó: {{ item.metadata.name | default('Nó sem nome') }}"
      - "Condição node_is_actually_ready_now: {{ node_is_actually_ready_now }}"
      - "Valor ATUAL _temp_nodes_ready_count: {{ _temp_nodes_ready_count }}"
      - "Tipo ATUAL _temp_nodes_ready_count: {{ _temp_nodes_ready_count | type_debug }}"
      - "Lista ATUAL _temp_nodes_not_ready_list: {{ _temp_nodes_not_ready_list }}"
  when: ansible_verbosity > 2 # Mostra apenas com -vvv

- name: "ATUALIZAR _temp_nodes_ready_count SE Nó ({{ item.metadata.name | default('Nó sem nome') }}) está pronto"
  ansible.builtin.set_fact:
    _temp_nodes_ready_count: "{{ (_temp_nodes_ready_count | int) + 1 }}"
  when: node_is_actually_ready_now

- name: "ATUALIZAR _temp_nodes_not_ready_list SE Nó ({{ item.metadata.name | default('Nó sem nome') }}) NÃO está pronto"
  ansible.builtin.set_fact:
    _temp_nodes_not_ready_list: "{{ _temp_nodes_not_ready_list + [item.metadata.name ~ ''] }}" # item.metadata.name é garantido existir pelo when do include_tasks
  when: not node_is_actually_ready_now

- name: "DEBUG NÓ ({{ item.metadata.name | default('Nó sem nome') }}) - APÓS atualização de contadores"
  ansible.builtin.debug:
    msg:
      - "Nó: {{ item.metadata.name | default('Nó sem nome') }}"
      - "Valor NOVO _temp_nodes_ready_count: {{ _temp_nodes_ready_count }}"
      - "Tipo NOVO _temp_nodes_ready_count: {{ _temp_nodes_ready_count | type_debug }}"
      - "Lista NOVA _temp_nodes_not_ready_list: {{ _temp_nodes_not_ready_list }}"
  when: ansible_verbosity > 2 # Mostra apenas com -vvv